import{i as A,S as g}from"./assets/vendor-46aac873.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const m="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEpSURBVHgBrZXtEcIgDIZTzp5/3URHcSPpJLpBXcVd+FPwiqQt1y+SUNv3DuUkvA+0SQQg5Jx7WOt8zsBYyudEmXsPuijg3bbtB1ipa/jQYQ+UZVmBpHjyprEvyBTGSjf52zwbssdchBxhTkI4c2vtTTJMxcwgw6RObZReXDycMSYBcTWuQX/6RqcMQpCmIOPNHbG30SKAgkjmU8AJBJ3PpQ5GOO2KCYVFGEaFa9J+EbCEDIAsc5SCTCkFPjWXlHWD2Jvw5MNP2b1HBEzN42OZvhMRwmURly1cCvfrszSlC41PxR6SKjQs3g4Qg6z9PpdBxsitIhWDXrPDcZCtWplHHQEhzY+AiOZ7IJz5qg5iWygK/wjfFwD+T18pdfXe37e0j07jTeTBPZYfWztI8097RKsAAAAASUVORK5CYII=",u="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAABOSURBVHgBzZLLDQAgCEOJE7H/Eo7gKKh3wJrGSBNOvEL4iJSRmfUVCnC62SgxsiJHJgOQBiEImz3DtdkpkpqbvBA1ArVE6oz0I9Gv/E0TMz3NWV1lPHoAAAAASUVORK5CYII=",p=document.querySelector(".search-img");document.querySelector(".button-search");const c=document.querySelector(".form"),l=document.querySelector(".gallery-list"),a=document.querySelector(".loader");a.style.display="none";c.addEventListener("submit",d);function d(i){i.preventDefault();const r=p.value;r!==""&&(l.textContent="",a.style.display="block",y(r).then(({hits:o})=>{if(o.length===0)A.show({message:'"Sorry, there are no images matching your search query. Please try again!"',backgroundColor:"#EF4040",messageColor:"#FFF",messageSize:"16px",position:"topRight",titleLineHeight:"1.5",iconUrl:m,close:!1,buttons:[[`<button type="button" style="background-color:#EF4040"><img src=${u}></button>`,function(s,e){s.hide({transitionOut:"fadeOut"},e)}]]});else{const s=o.map(f).join("");l.innerHTML=s,new g(".gallery-list a").refresh()}}).catch(o=>console.log("ERROR:",o)).finally(o=>{c.reset(),a.style.display="none"}))}function f({webformatURL:i,largeImageURL:r,tags:o,likes:s,views:e,comments:t,downloads:n}){return`
 <a href="${r}" class="gallery">
 <figure class="gallery-figure"> 
  <img src="${i}" alt="${o}" class="gallery-img"/>
  <figcaption class="gallery-figcaption">
  <div class="img-item">Likes <span class="img-elem">${s}</span></div>
  <div class="img-item">View <span class="img-elem">${e}</span></div>
  <div class="img-item">Comments <span class="img-elem">${t}</span></div>
  <div class="img-item">Downloads <span class="img-elem">${n}</span></div>
  </figcaption>
  </figure>
  </a>`}function y(i){const r="https://pixabay.com/api/",o=new URLSearchParams({key:"42200986-2d8f017897691a4245488f945",q:i,image_type:"photo",orientation:"horizontal",safeSearch:!0}),s=`${r}?${o}`;return fetch(s).then(e=>e.json()).catch(e=>{throw new Error(e.status)})}
//# sourceMappingURL=commonHelpers.js.map
