import{i as l,S as m}from"./assets/vendor-46aac873.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const g="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEpSURBVHgBrZXtEcIgDIZTzp5/3URHcSPpJLpBXcVd+FPwiqQt1y+SUNv3DuUkvA+0SQQg5Jx7WOt8zsBYyudEmXsPuijg3bbtB1ipa/jQYQ+UZVmBpHjyprEvyBTGSjf52zwbssdchBxhTkI4c2vtTTJMxcwgw6RObZReXDycMSYBcTWuQX/6RqcMQpCmIOPNHbG30SKAgkjmU8AJBJ3PpQ5GOO2KCYVFGEaFa9J+EbCEDIAsc5SCTCkFPjWXlHWD2Jvw5MNP2b1HBEzN42OZvhMRwmURly1cCvfrszSlC41PxR6SKjQs3g4Qg6z9PpdBxsitIhWDXrPDcZCtWplHHQEhzY+AiOZ7IJz5qg5iWygK/wjfFwD+T18pdfXe37e0j07jTeTBPZYfWztI8097RKsAAAAASUVORK5CYII=",u="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAABOSURBVHgBzZLLDQAgCEOJE7H/Eo7gKKh3wJrGSBNOvEL4iJSRmfUVCnC62SgxsiJHJgOQBiEImz3DtdkpkpqbvBA1ArVE6oz0I9Gv/E0TMz3NWV1lPHoAAAAASUVORK5CYII=",p=document.querySelector(".search-img");document.querySelector(".button-search");const c=document.querySelector(".form"),A=document.querySelector(".gallery"),a=document.querySelector(".loader");c.addEventListener("submit",d);function d(r){r.preventDefault();const o=p.value;o!==""&&(A.textContent="",a.style.display="block",y(o).then(function({hits:i}){if(i.length===0)l.show({message:'"Sorry, there are no images matching your search query. Please try again!"',backgroundColor:"#EF4040",messageColor:"#FFF",messageSize:"16px",position:"topRight",titleLineHeight:"1.5",iconUrl:g,close:!1,buttons:[[`<button type="button" style="background-color:#EF4040"><img src=${u}></button>`,function(s,e){s.hide({transitionOut:"fadeOut"},e)}]]});else{const s=i.map(f).join("");A.innerHTML=s,new m(".gallery a").refresh()}c.reset(),a.style.display="none"}))}function f({webformatURL:r,largeImageURL:o,tags:i,likes:s,views:e,comments:t,downloads:n}){return`
 <a href="${o}" class="gallery">
 <figure> 
  <img src="${r}" alt="${i}" class="gallery-img"/>
  <figcaption class="gallery-figcaption">
  <div class="img-item">Likes <span class="img-elem">${s}</span></div>
  <div class="img-item">View <span class="img-elem">${e}</span></div>
  <div class="img-item">Comments <span class="img-elem">${t}</span></div>
  <div class="img-item">Downloads <span class="img-elem">${n}</span></div>
  </figcaption>
  </figure>
  </a>`}function y(r){const o="https://pixabay.com/api/",i=new URLSearchParams({key:"42200986-2d8f017897691a4245488f945",q:r,image_type:"photo",orientation:"horizontal",safeSearch:!0}),s=`${o}?${i}`;return fetch(s).then(e=>e.json())}
//# sourceMappingURL=commonHelpers.js.map
